Vagrant.configure("2") do |config|
  config.vm.define "prueba-jenkins" do |desafio|
    # Usar Ubuntu 22.04 LTS (Jammy)
    desafio.vm.box = "ubuntu/jammy64"

    # Habilitar el reenvío de puertos
    desafio.vm.network "forwarded_port", guest: 8080, host: 8080  # Jenkins
    desafio.vm.network "forwarded_port", guest: 9090, host: 9090  # Prometheus
    desafio.vm.network "forwarded_port", guest: 3000, host: 3000  # Grafana
    desafio.vm.network "forwarded_port", guest: 9000, host: 9000  # SonarQube
    desafio.vm.network "forwarded_port", guest: 8081, host: 8081  # Mi aplicación

    # Configuración del proveedor VirtualBox
    desafio.vm.provider "virtualbox" do |vb|
      vb.name = "prueba-jenkins"
      vb.memory = "4096"
      vb.cpus = 4
    end

    # Ejecutar el script de bootstrap para instalar aplicaciones
    desafio.vm.provision "shell", path: "bootstrap.sh"
  end
end
