Vagrant.configure("2") do |config|
  config.vm.define "prueba-jenkins" do |desafio|
    desafio.vm.box = "ubuntu/focal64"
  end

  # Habilitar el reenvío de puerto
  config.vm.network "forwarded_port", guest: 8080, host: 8080  # Jenkins
  config.vm.network "forwarded_port", guest: 9090, host: 9090  # Prometheus
  config.vm.network "forwarded_port", guest: 3000, host: 3000  # Grafana
  config.vm.network "forwarded_port", guest: 9000, host: 9001  # SonarQube


  # Configuración del proveedor VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "prueba-jenkins"
    vb.memory = "6144"
    vb.cpus = 4
  end

  # Ejecutar el script de bootstrap para instalar aplicaciones
  config.vm.provision "shell", path: "bootstrap.sh"
end
